#!/bin/bash
# Important Commands to execute:
# a).bashrc setup
# b) don't forget to install amd64 versions of 32 bit libs
#Then do these:
#
#Build prerequisites:
sudo apt-get update
sudo apt-get upgrade
sudo apt-get -y install git subversion libmpc-dev libmpfr-dev libgmp-dev python-dev texinfo libisl-dev phablet-tools \
automake perl libcloog-isl-dev git-core gnupg flex bison gperf build-essential \
zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev libtool autogen pigz \
lib32ncurses5-dev x11proto-core-dev libx11-dev ccache liblz4-tool \
libgl1-mesa-dev libxml2-utils xsltproc unzip default-jre default-jdk pigz gdb \
pngcrush schedtool squashfs-tools readline-common lib32z1-dev \
android-headers yasm
echo "Setting .bashrc"
rm -f ~/.bashrc ~/.gitconfig
cp bashrcbck ~/.bashrc
cp gitconfig ~/.gitconfig
source ~/.bashrc
echo "Done"