#!/bin/bash
# Important Commands to execute:
# a).bashrc setup
# b) don't forget to install amd64 versions of 32 bit libs
# Then do these:
#
# Setup CLI Software:
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install git python-dev gnupg zip curl unzip pigz libxml2-utils
if [[ -e bashrcbck ]];
then
	echo "Setting .bashrc"
	mv ~/.bashrc ~/.bashrc.bak
	mv ~/.gitconfig ~/.gitconfig.bak
	cp bashrcbck ~/.bashrc
	cp gitconfig ~/.gitconfig
	source ~/.bashrc
	echo "Done"
fi
